name: Buildness check

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  ubuntu-build:
    name: Ubuntu 24
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install g++ make
    - name: Build
      run: |
           ./configure
           make
    - name: Run tests
      run: ./build/tests

  macos-build:
    name: MacOS
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: brew install llvm make
    - name: Build
      run: |
           ./configure
           make
    - name: Run tests
      run: ./build/tests
