name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build for Ubuntu 24
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install g++ make
    - name: Build
      run: make
    - name: Run tests
      run: ./build/tests
