name: Buildness check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  ubuntu-build:
    name: Ubuntu 20
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install g++ make
    - name: Build
      run: |
           ./configure
           make
    - name: Run tests
      run: ./build/tests
    - name: Upload build 
      uses: actions/upload-artifact@v4.4.3
      with: 
        name: ubuntu
        path: build

  macos-build:
    name: MacOS
    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: brew install make
    - name: Build
      run: |
           ./configure
           make
    - name: Run tests
      run: |
           ./build/tests
           mv ./build/algebra ./build/algebra-osx
    - name: Upload build 
      uses: actions/upload-artifact@v4.4.3
      with: 
        name: mac
        path: build
  
  windows-build:
    name: Windows 10
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Install make with Chocolatey
      uses: crazy-max/ghaction-chocolatey@v3.0.0
      with:
        args: install make
    - name: Build
      shell: bash
      run: |
           ./configure
           make
    - name: Run tests
      shell: bash
      run: |
           ./build/tests
           mv ./build/algebra ./build/algebra-win.exe
    - name: Upload build 
      uses: actions/upload-artifact@v4.4.3
      with: 
        name: windows
        path: build

  upload: 
    name: Upload
    needs: [ubuntu-build, macos-build, windows-build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v4
    - name: Download Ubuntu artifact 
      uses: actions/download-artifact@v4 
      with:
        name: ubuntu 
    - name: Download macOS artifact 
      uses: actions/download-artifact@v4
      with:
        name: mac 
    - name: Download Windows artifact
      uses: actions/download-artifact@v4 
      with:
        name: win
    - name: Upload to Release (Ubuntu)
      uses: JasonEtco/upload-to-release@master 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        args: ubuntu/algebra application/x-executable 
    - name: Upload to Release (macOS)
      uses: JasonEtco/upload-to-release@master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        args: mac/algebra-osx application/x-executable 
    - name: Upload to Release (Windows)
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with: 
        args: win/win.exe application/octet-stream
