name: Upload release

on: release


jobs:
  ubuntu-build:
    name: Ubuntu 20
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install g++ make
    - name: Build
      run: |
           ./configure
           make algebra
    - name: Upload build 
      uses: actions/upload-artifact@v3.0.0
      with: 
        name: ubuntu
        path: build

  macos-build:
    name: MacOS
    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: brew install make
    - name: Build
      run: |
           ./configure
           make algebra
           mv ./build/algebra ./build/algebra-osx
    - name: Upload build 
      uses: actions/upload-artifact@v3.0.0
      with: 
        name: mac
        path: build
  
  windows-build:
    name: Windows 10
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Install make with Chocolatey
      uses: crazy-max/ghaction-chocolatey@v3.0.0
      with:
        args: install make
    - name: Build
      shell: bash
      run: |
           ./configure
           make algebra
           mv ./build/algebra ./build/algebra-win.exe
    - name: Upload build 
      uses: actions/upload-artifact@v3.0.0
      with: 
        name: windows
        path: build

  upload: 
    name: Upload
    needs: [ubuntu-build, macos-build, windows-build]
    runs-on: ubuntu-latest 
    steps: 
    - name: Prepare workspace
      run: |
           mkdir ubuntu
           mkdir ubuntu/tests
           mkdir mac
           mkdir mac/tests
           mkdir windows
           mkdir windows/tests
    - name: Download Ubuntu artifact 
      uses: actions/download-artifact@v3.0.0
      with:
        name: ubuntu 
    - name: Download macOS artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: mac 
    - name: Download Windows artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: windows
    - name: Upload to Release (Ubuntu)
      uses: JasonEtco/upload-to-release@master 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        args: algebra application/x-executable 
    - name: Upload to Release (macOS)
      uses: JasonEtco/upload-to-release@master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        args: algebra-osx application/x-executable 
    - name: Upload to Release (Windows)
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with: 
        args: algebra-win.exe application/octet-stream
